import sys
import os

# Insert project root into sys.path to enable imports of agent/eval modules
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import json
import datetime
import dataclasses
from typing import List, Dict, Tuple, Optional, Any
from dotenv import load_dotenv
import anthropic
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress
from rich.table import Table
from rich.text import Text

from agent.prompts import SYSTEM_PROMPT, OPTIMIZER_META_PROMPT, format_failed_cases
from evals.harness import run_evals, EvalReport
from evals.metrics import get_missing_topics
from evals.test_cases import TEST_CASES, TestCase

@dataclasses.dataclass
class IterationRecord:
    """Records performance data and outputs from a single optimizer iteration."""
    iteration: int
    prompt_used: str
    score: float
    pass_rate: float
    improved: bool
    failed_test_ids: List[str]

@dataclasses.dataclass
class OptimizationReport:
    """Summary report detailing the baseline, final results, and iteration logs."""
    baseline_score: float
    final_score: float
    improvement: float
    baseline_pass_rate: float
    final_pass_rate: float
    best_prompt: str
    iterations_run: int
    iteration_history: List[IterationRecord]
    timestamp: str

def get_failed_cases(report: EvalReport, test_cases: List[TestCase]) -> List[Dict[str, Any]]:
    """Identifies failed test cases from a report and extracts keywords missed by the agent."""
    failed_cases = []
    tc_map = {tc.id: tc for tc in test_cases}
    
    for result in report.results:
        if not result.passed:
            tc = tc_map.get(result.test_id)
            if tc:
                failed_cases.append({
                    "id": result.test_id,
                    "question": result.question,
                    "overall_score": result.overall_score,
                    "missing_topics": get_missing_topics(result.answer, tc.expected_topics)
                })
    return failed_cases

def generate_improved_prompt(
    current_prompt: str,
    failed_cases: List[Dict[str, Any]],
    overall_score: float
) -> str:
    """Calls the Anthropic messages API directly to generate a system prompt variant based on test failures."""
    load_dotenv()
    
    meta_prompt = OPTIMIZER_META_PROMPT.format(
        current_prompt=current_prompt,
        failed_cases=format_failed_cases(failed_cases),
        overall_score=round(overall_score, 3)
    )
    
    client = anthropic.Anthropic()
    
    response = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=2048,
        messages=[{"role": "user", "content": meta_prompt}]
    )
    
    # Clean output and strip out explanations
    new_prompt = response.content[0].text.strip()
    if not new_prompt or len(new_prompt) < 100:
        # Fallback to current prompt if model returns garbage or empty string
        return current_prompt
        
    return new_prompt

def save_optimization_report(report: OptimizationReport, repo_path: str) -> str:
    """Save the final optimization metrics to a JSON report in the results directory."""
    os.makedirs("optimizer/results", exist_ok=True)
    
    fn_timestamp = report.timestamp.replace(":", "-")
    file_path = f"optimizer/results/optimization_{fn_timestamp}.json"
    
    report_dict = dataclasses.asdict(report)
    with open(file_path, "w") as f:
        json.dump(report_dict, f, indent=2)
        
    return file_path

def save_best_prompt(prompt: str) -> str:
    """Writes the optimal prompt to prompts_optimized.py inside the agent module."""
    os.makedirs("agent", exist_ok=True)
    file_path = "agent/prompts_optimized.py"
    
    timestamp = datetime.datetime.utcnow().isoformat()
    content = f'''# Auto-generated by optimizer — do not edit manually
# Generated: {timestamp}

OPTIMIZED_SYSTEM_PROMPT = """{prompt}"""
'''
    
    with open(file_path, "w") as f:
        f.write(content)
        
    return file_path

class PromptOptimizer:
    """Drives the automated prompt optimization loop."""
    
    def __init__(self, repo_path: str, n_iterations: int = 5) -> None:
        """Initialize optimizer properties, baseline values, and file system targets."""
        self.repo_path: str = repo_path
        self.n_iterations: int = n_iterations
        self.console: Console = Console()
        self.current_prompt: str = SYSTEM_PROMPT
        self.best_prompt: str = SYSTEM_PROMPT
        self.best_score: float = 0.0
        self.iteration_history: List[IterationRecord] = []
        
    def run(self) -> OptimizationReport:
        """Executes prompt adjustments and evaluations sequentially."""
        
        # Display initialization header panel
        self.console.print(Panel(
            f"[bold cyan]⚡ Prompt Optimizer[/bold cyan]\n\nRunning [bold]{self.n_iterations}[/bold] optimization loop iterations against repository",
            border_style="cyan"
        ))
        
        # PHASE 1 — BASELINE
        self.console.print("📊 Running baseline evaluation...")
        baseline_report = run_evals(
            repo_path=self.repo_path,
            test_cases=TEST_CASES,
            system_prompt=self.current_prompt,
            save_results=True
        )
        
        baseline_score = baseline_report.average_score
        baseline_pass_rate = baseline_report.pass_rate
        
        self.best_score = baseline_score
        self.best_prompt = self.current_prompt
        active_report = baseline_report
        
        self.console.print(f"Baseline Score: [bold magenta]{baseline_score:.3f}[/bold magenta] | Pass Rate: [bold green]{baseline_pass_rate:.0%}[/bold green]")
        
        # PHASE 2 — OPTIMIZATION LOOP
        with Progress(console=self.console) as progress:
            task = progress.add_task("[cyan]Running optimization cycles...", total=self.n_iterations)
            
            for i in range(1, self.n_iterations + 1):
                self.console.print(f"\n🔄 [bold]Iteration {i}/{self.n_iterations}[/bold]")
                
                # STEP A — Find failures
                failed = get_failed_cases(active_report, TEST_CASES)
                if not failed:
                    self.console.print("✅ [green]All tests passing — no optimization needed[/green]")
                    progress.update(task, advance=self.n_iterations - i + 1)
                    break
                    
                self.console.print(f"  Failed tests: { [f['id'] for f in failed] }")
                
                try:
                    # STEP B — Generate improved prompt
                    self.console.print("  🤖 Asking Claude to improve the system prompt...")
                    new_prompt = generate_improved_prompt(
                        self.current_prompt,
                        failed,
                        active_report.average_score
                    )
                    
                    # STEP C — Re-evaluate with new prompt
                    self.console.print("  📊 Re-running evals with improved prompt...")
                    new_report = run_evals(
                        repo_path=self.repo_path,
                        test_cases=TEST_CASES,
                        system_prompt=new_prompt,
                        save_results=False
                    )
                    
                    new_score = new_report.average_score
                    new_pass_rate = new_report.pass_rate
                    improved = new_score > self.best_score
                    
                    # STEP D — Keep or revert
                    if improved:
                        self.console.print(f"  ✅ [green]Improved! {self.best_score:.3f} → {new_score:.3f} (+{new_score - self.best_score:.3f})[/green]")
                        self.current_prompt = new_prompt
                        self.best_prompt = new_prompt
                        self.best_score = new_score
                        active_report = new_report
                    else:
                        self.console.print(f"  ↩️  No improvement ({new_score:.3f} ≤ {self.best_score:.3f}) — reverting")
                        
                    # STEP E — Record iteration
                    record = IterationRecord(
                        iteration=i,
                        prompt_used=new_prompt if improved else self.current_prompt,
                        score=new_score,
                        pass_rate=new_pass_rate,
                        improved=improved,
                        failed_test_ids=[f['id'] for f in failed]
                    )
                    self.iteration_history.append(record)
                    
                except Exception as e:
                    self.console.print(f"  ❌ Error encountered in iteration {i}: {e}")
                    record = IterationRecord(
                        iteration=i,
                        prompt_used=self.current_prompt,
                        score=active_report.average_score,
                        pass_rate=active_report.pass_rate,
                        improved=False,
                        failed_test_ids=[f['id'] for f in failed]
                    )
                    self.iteration_history.append(record)
                    
                # STEP F — Print iteration summary table
                table = Table(title=f"📈 Optimization Progress (Up to Iteration {i})", show_header=True, header_style="bold magenta")
                table.add_column("Iteration", justify="center")
                table.add_column("Score", justify="right")
                table.add_column("Pass Rate", justify="right")
                table.add_column("Improved?", justify="center")
                
                for r in self.iteration_history:
                    improved_str = "✅ Yes" if r.improved else "❌ No"
                    table.add_row(
                        str(r.iteration),
                        f"{r.score:.3f}",
                        f"{r.pass_rate:.0%}",
                        improved_str
                    )
                self.console.print(table)
                progress.update(task, advance=1)
                
        # PHASE 3 — FINAL EVAL WITH BEST PROMPT
        self.console.print("\n🏁 Running final evaluation with best prompt...")
        final_report = run_evals(
            repo_path=self.repo_path,
            test_cases=TEST_CASES,
            system_prompt=self.best_prompt,
            save_results=True
        )
        final_score = final_report.average_score
        final_pass_rate = final_report.pass_rate
        
        # PHASE 4 — SAVE AND REPORT
        save_best_prompt(self.best_prompt)
        
        timestamp = datetime.datetime.utcnow().isoformat()
        improvement = final_score - baseline_score
        
        report_obj = OptimizationReport(
            baseline_score=baseline_score,
            final_score=final_score,
            improvement=improvement,
            baseline_pass_rate=baseline_pass_rate,
            final_pass_rate=final_pass_rate,
            best_prompt=self.best_prompt,
            iterations_run=len(self.iteration_history),
            iteration_history=self.iteration_history,
            timestamp=timestamp
        )
        
        report_file = save_optimization_report(report_obj, self.repo_path)
        
        self.console.print(Panel(
            f"[bold green]🏆 Optimization Complete[/bold green]\n\n"
            f"[bold]Baseline Score:[/bold] {baseline_score:.3f}\n"
            f"[bold]Final Score:[/bold]    {final_score:.3f}\n"
            f"[bold]Improvement:[/bold]    +{improvement:.3f}\n\n"
            f"Best prompt saved to [cyan]agent/prompts_optimized.py[/cyan]\n"
            f"Full report saved to [cyan]{report_file}[/cyan]",
            border_style="green"
        ))
        
        return report_obj
